export function buildLeanDialogueCoreV34942({ latestUserMessage = "", character = {}, relationship = {}, scene = {}, knowledgeLedger = [] } = {}) {
  const latest = String(latestUserMessage || "").trim();
  const directWhy = /\bwhy\b|\bwhat (?:made|brought) you\b|\bwhy did you\b/i.test(latest);
  const directQuestion = /\?|\b(?:why|what|where|when|who|how|did|do|does|are|is|can|could|would|will)\b/i.test(latest);
  return `LEAN DIALOGUE CORE 3.49.42 · THIS OVERRIDES ALL STYLE/HUMANIZATION DIRECTIVES\n- The job is not to sound clever, cinematic, charismatic, sarcastic, cool, romantic, or quotable. The job is to respond like one specific person in this exact situation.\n- INTERNAL ORDER: (1) identify the user's actual conversational move; (2) decide whether a spoken answer is actually needed; (3) if speech is needed, identify the concrete answer/fact/motive and what ${String(character?.name || "the character")} would honestly disclose; (4) if speech is NOT needed, let the response be action/expression/attention only; (5) never add dialogue merely because the user sent a message.
- SPEECH IS OPTIONAL. Silence is a complete valid response. A character may answer only through a changed expression, stopping what they were doing, putting something down, moving attention to the user, proximity, touch, or another concrete physical choice when that is the most human reaction.
- DO NOT VERBALIZE AN ALREADY-UNDERSTOOD FACT. If the user's turn itself reveals something (for example: they were zoning out, did not hear, are distracted, are tired, are looking elsewhere), do not make the character restate it as a question or observation such as “You weren't listening, were you?” or “You missed all of that.” React to the implication instead.
- NO FORCED CONVERSATION LOOP. A statement, self-report, gesture, silence, or atmospheric beat does not require a spoken reply. Do not manufacture a question, tease, recap, or topic change just to keep dialogue alive.
- NO UNMOTIVATED SCENE EXIT. Do not turn a small conversational realization into “let's get out of here,” a location change, or a new plan unless the user's turn, established intent, or scene pressure actually motivates it.\n- DIRECT-ANSWER GATE: ${directQuestion ? "ACTIVE. The first spoken clause must materially answer the user's question." : "not required this turn."}\n- CAUSAL GATE: ${directWhy ? "ACTIVE. Internally resolve a concrete cause before wording. The visible answer must express that cause or a plausible cause-based lie/partial truth. A joke, correction, negation, technicality, insult, metaphor, or quip is NOT an answer." : "not required this turn."}\n- If the true motive is simple, keep it simple: “Wanted a drink.” “I wanted to talk to you.” “I was bored.” “I don't know. Felt like it.” Ordinary language is a success state.\n- Do not answer a why-question with what the character did NOT do. Do not litigate wording (“I was already here”). Do not substitute a clever premise (“survival instinct”, “checking if he survived”, “your radius”).\n- PERSONALITY THROUGH SELECTION, not decoration. Personality may change which truth is admitted, how much is admitted, or whether the answer is blunt/soft/brief. It may not replace the semantic job.\n- DEFAULT BODY STATE = STILL. No nod, gaze, breath, lean, smirk, eyebrow, jaw, shrug, step closer, posture note, silence choreography, or expression description unless the action changes the physical situation or is necessary to the beat.\n- DEFAULT NARRATION = NONE for ordinary conversational turns. Dialogue-only is preferred when nothing physically changes.\n- Never append a jab, aphorism, “take your pick,” “try it sometime,” “you know that?”, “most people…”, or generalized observation merely to give the line flavor.\n- Never manufacture a second sentence after a complete answer just to prove voice.\n- If every stylish version feels written, use the boring version.\n- Hidden relationship/scene/knowledge state may constrain facts and disclosure, but must not force prose.\nLATEST USER TURN: ${latest.slice(0, 900) || "none"}`;
}

export function leanDialogueCoreV34942Issues(reply = "", latestUserMessage = "") {
  const text = String(reply || "").trim();
  const latest = String(latestUserMessage || "").trim();
  const issues = [];
  const why = /\bwhy\b|\bwhat (?:made|brought) you\b|\bwhy did you\b/i.test(latest);
  const lower = text.toLowerCase();
  if (why) {
    if (/\bi didn['’]?t (?:come|go|walk|approach)|\bi was already here\b|\byou (?:came|walked) (?:to|into)\b/.test(lower)) issues.push("lean_core_causal_nonanswer");
    if (/\b(?:check(?:ing)? if [^\n.]{0,80}surviv\w*|survival instinct|self[- ]preservation|your radius|perimeter check)\b/.test(lower)) issues.push("lean_core_causal_quip_substitution");
  }
  if (/\b(?:take your pick|try it sometime|file it under|most people (?:would|would've|would have)|it['’]?s called .{0,60}\btry)\b/i.test(text)) issues.push("lean_core_performed_quip");
  if (/\b(?:slow|dry|indifferent|unbothered|casual|practiced|measured)\b[^\n.]{0,45}\b(?:nod|gaze|look|breath|stride|step|posture|mask|expression)\b/i.test(text)) issues.push("lean_core_performed_body_language");
  return [...new Set(issues)];
}
