import { BookOpen, CalendarDays, GitBranch, Link2, Plus, Save, Sparkles, Trash2, UserPlus, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "../services/supabase";

const empty={bible:{category:"world",title:"",content:"",authority:"canon"},npc:{name:"",role:"",personality_note:"",relationship:"",current_dynamic:"",goals:"",knowledge:"",presence:"off_scene",status:"active"},connection:{from_name:"",to_name:"",relationship:"",visibility:"known"},event:{title:"",story_time:"",details:"",participants:"",status:"upcoming"},arc:{title:"",summary:"",kind:"relationship",status:"active",progress:0,stakes:"",next_pressure:"",participants:""},knowledge:{character_name:"",subject:"",knowledge:"",status:"known",source:"",secret:false},consequence:{title:"",cause:"",effect:"",status:"pending",weight:2,participants:""},chemistry:{character_name:"",signature:"",banter_style:"",affection_style:"",friction_triggers:"",reconciliation_style:"",inside_jokes:"",meaningful_places:"",chemistry_score:25,trust_score:20,tension_score:10},plan:{title:"",initiator:"",details:"",story_time:"",participants:"",status:"proposed",complication:""},conflict:{title:"",cause:"",positions:"",intensity:2,status:"active",resolution_need:"",repair_attempts:0,participants:""},milestone:{milestone_type:"custom",title:"",details:"",participants:"",story_time:""}};
const tables={bible:"story_bible_entries",npc:"story_cast_members",connection:"story_cast_connections",event:"story_calendar_events",arc:"story_arcs",knowledge:"story_knowledge_entries",consequence:"story_consequences",chemistry:"story_chemistry_profiles",plan:"story_plans",conflict:"story_conflicts",milestone:"story_milestones"};
const tabs=[["bible",BookOpen,"Bible"],["npc",UserPlus,"NPCs"],["connection",Link2,"Bonds"],["event",CalendarDays,"Calendar"],["arc",GitBranch,"Arcs"],["knowledge",Users,"Knowledge"],["consequence",Sparkles,"Consequences"],["chemistry",Sparkles,"Chemistry"],["plan",CalendarDays,"Plans"],["conflict",GitBranch,"Conflicts"],["milestone",BookOpen,"Milestones"]];
const people=(value)=>Array.isArray(value)?value:String(value||"").split(",").map((x)=>x.trim()).filter(Boolean);

export default function StoryWorldDrawer({open,onClose,conversationId}){
 const [tab,setTab]=useState("bible"),[data,setData]=useState(Object.fromEntries(Object.keys(tables).map((k)=>[k,[]]))),[drafts,setDrafts]=useState(empty),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){if(!conversationId)return;const keys=Object.keys(tables),results=await Promise.all(keys.map((k)=>supabase.from(tables[k]).select("*").eq("conversation_id",conversationId).order("updated_at",{ascending:false})));setData(Object.fromEntries(keys.map((k,i)=>[k,results[i].data||[]])));const error=results.find((x)=>x.error)?.error;if(error)setNotice(error.message)}
 useEffect(()=>{if(open)load()},[open,conversationId]);if(!open)return null;
 const draft=(field,value)=>setDrafts((s)=>({...s,[tab]:{...s[tab],[field]:value}}));const edit=(id,field,value)=>setData((s)=>({...s,[tab]:s[tab].map((x)=>x.id===id?{...x,[field]:value}:x)}));
 async function add(){setBusy(true);const{data:auth}=await supabase.auth.getUser();let row={...drafts[tab],user_id:auth?.user?.id,conversation_id:conversationId,updated_at:new Date().toISOString()};if(["event","arc","consequence","plan","conflict","milestone"].includes(tab))row.participants=people(row.participants);if(tab==="chemistry"){row.inside_jokes=people(row.inside_jokes);row.meaningful_places=people(row.meaningful_places)}if(tab==="npc")row.turn_count=0;const{error}=await supabase.from(tables[tab]).insert(row);if(!error){setDrafts((s)=>({...s,[tab]:{...empty[tab]}}));await load()}setNotice(error?error.message:"Saved.");setBusy(false)}
 async function update(item){setBusy(true);const row={...item,updated_at:new Date().toISOString()};["id","user_id","conversation_id","created_at"].forEach((k)=>delete row[k]);if(["event","arc","consequence","plan","conflict","milestone"].includes(tab))row.participants=people(row.participants);if(tab==="chemistry"){row.inside_jokes=people(row.inside_jokes);row.meaningful_places=people(row.meaningful_places)}const{error}=await supabase.from(tables[tab]).update(row).eq("id",item.id);setNotice(error?error.message:"Changes saved.");setBusy(false)}
 async function remove(item){setBusy(true);const{error}=await supabase.from(tables[tab]).delete().eq("id",item.id);if(!error)setData((s)=>({...s,[tab]:s[tab].filter((x)=>x.id!==item.id)}));setNotice(error?error.message:"Removed.");setBusy(false)}
 return <div className="world-studio-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><aside className="world-studio" role="dialog" aria-modal="true"><header><div><small>STORY ENGINE 3.4</small><h2>World Studio</h2><p>Build chemistry, plans, conflict and the moments that change a relationship.</p></div><button onClick={onClose}><X size={19}/></button></header><nav>{tabs.map(([id,Icon,label])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</nav><section className="world-studio__section"><div className="world-studio__new"><h3>{titles[tab]}</h3><Fields kind={tab} item={drafts[tab]} set={draft}/><button onClick={add} disabled={busy||!valid(tab,drafts[tab])}><Plus size={15}/>Add</button></div><div className="world-studio__entries">{data[tab].map((item)=><article className="world-studio__card" key={item.id}><strong>{label(tab,item)}</strong><Fields kind={tab} item={item} set={(field,value)=>edit(item.id,field,value)} editing/><div><button onClick={()=>remove(item)}><Trash2 size={14}/>Remove</button><button onClick={()=>update(item)}><Save size={14}/>Save</button></div></article>)}</div></section>{notice&&<footer role="status">{notice}</footer>}</aside></div>
}
const titles={bible:"New permanent fact",npc:"Create recurring NPC",connection:"Connect two people",event:"Schedule story event",arc:"Create a playable arc",knowledge:"Record who knows what",consequence:"Create a lasting consequence",chemistry:"Define this couple's unique chemistry",plan:"Create a real future plan",conflict:"Record a conflict that cannot vanish",milestone:"Record a relationship milestone"};
function label(k,x){if(k==="connection")return `${x.from_name} ↔ ${x.to_name}`;if(k==="event")return `${x.title} · ${x.story_time}`;if(k==="knowledge")return `${x.character_name} · ${x.subject}`;if(k==="chemistry")return `Chemistry · ${x.character_name}`;return x.title||x.name}
function valid(k,x){if(k==="npc")return x.name.trim();if(k==="connection")return x.from_name.trim()&&x.to_name.trim()&&x.relationship.trim();if(k==="event")return x.title.trim()&&x.story_time.trim();if(k==="knowledge")return x.character_name.trim()&&x.subject.trim()&&x.knowledge.trim();if(k==="consequence")return x.title.trim()&&x.cause.trim()&&x.effect.trim();if(k==="chemistry")return x.character_name.trim();if(k==="conflict")return x.title.trim()&&x.cause.trim();return x.title.trim()&&(k!=="bible"||x.content.trim())}
const T=({item,set,name,placeholder,one=false})=>one?<input placeholder={placeholder} value={Array.isArray(item[name])?item[name].join(", "):item[name]??""} onChange={(e)=>set(name,e.target.value)}/>:<textarea rows="2" placeholder={placeholder} value={item[name]??""} onChange={(e)=>set(name,e.target.value)}/>;
const S=({item,set,name,options})=><select value={item[name]} onChange={(e)=>set(name,e.target.value)}>{options.map((x)=><option key={x} value={x}>{x}</option>)}</select>;
function Fields({kind:k,item:x,set,editing=false}){
 if(k==="bible")return <>{!editing&&<T item={x} set={set} name="title" placeholder="Title" one/>}<T item={x} set={set} name="content" placeholder="What is permanently true?"/><S item={x} set={set} name="authority" options={["canon","private","tentative"]}/></>;
 if(k==="npc")return <>{(!editing?["name"]:[]).concat(["role","personality_note","relationship","current_dynamic","goals","knowledge"]).map((n)=><T key={n} item={x} set={set} name={n} placeholder={n.replaceAll("_"," ")}/>)}</>;
 if(k==="connection")return <>{!editing&&<><T item={x} set={set} name="from_name" placeholder="From" one/><T item={x} set={set} name="to_name" placeholder="To" one/></>}<T item={x} set={set} name="relationship" placeholder="Their relationship"/></>;
 if(k==="event")return <>{!editing&&<T item={x} set={set} name="title" placeholder="Event" one/>}<T item={x} set={set} name="story_time" placeholder="Story time: Saturday night, after finals…" one/><T item={x} set={set} name="details" placeholder="Pressure or opportunity"/><T item={x} set={set} name="participants" placeholder="Participants, comma separated" one/><S item={x} set={set} name="status" options={["upcoming","active","completed","cancelled"]}/></>;
 if(k==="arc")return <>{!editing&&<T item={x} set={set} name="title" placeholder="Arc title" one/>}<T item={x} set={set} name="summary" placeholder="What is developing?"/><S item={x} set={set} name="kind" options={["relationship","romance","social","rivalry","mystery","external"]}/><T item={x} set={set} name="stakes" placeholder="What can be gained or lost?"/><T item={x} set={set} name="next_pressure" placeholder="Next concrete pressure"/><T item={x} set={set} name="participants" placeholder="Participants" one/><label>Progress: {x.progress||0}%<input type="range" min="0" max="100" value={x.progress||0} onChange={(e)=>set("progress",Number(e.target.value))}/></label><S item={x} set={set} name="status" options={["planned","active","paused","resolved"]}/></>;
 if(k==="knowledge")return <><T item={x} set={set} name="character_name" placeholder="Who knows it?" one/><T item={x} set={set} name="subject" placeholder="Subject" one/><T item={x} set={set} name="knowledge" placeholder="Exactly what they know"/><T item={x} set={set} name="source" placeholder="How they learned it" one/><S item={x} set={set} name="status" options={["known","suspected","rumor","unknown"]}/><label className="world-studio__check"><input type="checkbox" checked={Boolean(x.secret)} onChange={(e)=>set("secret",e.target.checked)}/>Secret from protagonist</label></>;
 if(k==="chemistry")return <><T item={x} set={set} name="character_name" placeholder="Character" one/><T item={x} set={set} name="signature" placeholder="What makes this chemistry unique?"/><T item={x} set={set} name="banter_style" placeholder="How they tease or challenge each other"/><T item={x} set={set} name="affection_style" placeholder="How affection appears"/><T item={x} set={set} name="friction_triggers" placeholder="What reliably creates friction"/><T item={x} set={set} name="reconciliation_style" placeholder="How this character tries to repair things"/><T item={x} set={set} name="inside_jokes" placeholder="Inside jokes, comma separated" one/><T item={x} set={set} name="meaningful_places" placeholder="Meaningful places, comma separated" one/>{[["chemistry_score","Chemistry"],["trust_score","Trust"],["tension_score","Tension"]].map(([name,title])=><label key={name}>{title}: {x[name]||0}<input type="range" min="0" max="100" value={x[name]||0} onChange={(e)=>set(name,Number(e.target.value))}/></label>)}</>;
 if(k==="plan")return <>{!editing&&<T item={x} set={set} name="title" placeholder="Plan" one/>}<T item={x} set={set} name="initiator" placeholder="Who proposed it?" one/><T item={x} set={set} name="details" placeholder="Activity and concrete details"/><T item={x} set={set} name="story_time" placeholder="When in story time?" one/><T item={x} set={set} name="participants" placeholder="Participants" one/><T item={x} set={set} name="complication" placeholder="Possible complication"/><S item={x} set={set} name="status" options={["proposed","accepted","active","completed","cancelled","failed"]}/></>;
 if(k==="conflict")return <>{!editing&&<T item={x} set={set} name="title" placeholder="Conflict" one/>}<T item={x} set={set} name="cause" placeholder="Concrete cause"/><T item={x} set={set} name="positions" placeholder="What each side wants or believes"/><T item={x} set={set} name="resolution_need" placeholder="What real repair would require"/><T item={x} set={set} name="participants" placeholder="Participants" one/><label>Intensity: {x.intensity||2}<input type="range" min="1" max="5" value={x.intensity||2} onChange={(e)=>set("intensity",Number(e.target.value))}/></label><S item={x} set={set} name="status" options={["brewing","active","cooling","repairing","resolved"]}/></>;
 if(k==="milestone")return <><S item={x} set={set} name="milestone_type" options={["custom","first_invitation","first_hand_hold","first_kiss","first_real_fight","first_reconciliation","first_public_defense","met_friends","exclusive","breakup"]}/><T item={x} set={set} name="title" placeholder="Milestone title" one/><T item={x} set={set} name="details" placeholder="What actually happened on-page"/><T item={x} set={set} name="participants" placeholder="Participants" one/><T item={x} set={set} name="story_time" placeholder="Story time" one/></>;
 return <>{!editing&&<T item={x} set={set} name="title" placeholder="Consequence" one/>}<T item={x} set={set} name="cause" placeholder="What caused it?"/><T item={x} set={set} name="effect" placeholder="How it changes future scenes"/><T item={x} set={set} name="participants" placeholder="Affected people" one/><label>Weight: {x.weight||2}<input type="range" min="1" max="5" value={x.weight||2} onChange={(e)=>set("weight",Number(e.target.value))}/></label><S item={x} set={set} name="status" options={["pending","active","resolved"]}/></>;
}
