import { existsSync, readFileSync } from "node:fs";

const read = (file) => readFileSync(file, "utf8");
const main = read("src/main.jsx");
const app = read("src/App.jsx");
const chat = read("src/pages/Chat.jsx");
const mobile = read("src/styles/velvet-mobile-foundation.css");
const reference = read("src/styles/velvet-burgundy-reference.css");
const stories = read("src/pages/Chats.jsx");
const sidebar = read("src/components/Sidebar.jsx");
const settings = read("src/pages/Settings.jsx");
const memories = read("src/pages/Memories.jsx");
const diagnostics = read("src/pages/Diagnostics.jsx");
const characterModal = read("src/components/CreateCharacterModal.jsx");
const edge = read("supabase/functions/character-chat/index.ts");
const pkg = JSON.parse(read("package.json"));

const checks = [];
const check = (name, pass) => checks.push({ name, pass: Boolean(pass) });

check("burgundy reference layer is the final stylesheet", main.includes('import "./styles/velvet-burgundy-reference.css";') && main.lastIndexOf("velvet-burgundy-reference.css") > main.lastIndexOf("velvet-mobile-foundation.css"));
check("legacy mobile hotfix styles are no longer loaded", ["mobile-v71.css","velvet-v171-hotfix.css","velvet-v172-mobile-emergency.css","velvet-v181-guarded-swipe.css","velvet-v19-phone-first.css","velvet-v191-composer-hotfix.css","velvet-v192-message-sheet-portal.css","velvet-v193-mobile-geometry.css"].every((name)=>!main.includes(name)));
check("legacy mobile hotfix files were removed", ["mobile-v71.css","velvet-v171-hotfix.css","velvet-v172-mobile-emergency.css","velvet-v181-guarded-swipe.css","velvet-v19-phone-first.css","velvet-v191-composer-hotfix.css","velvet-v192-message-sheet-portal.css","velvet-v193-mobile-geometry.css"].every((name)=>!existsSync(`src/styles/${name}`)));
check("release is v2.2.0 Native Story Experience", pkg.version === "2.2.0" && read("src/config/version.js").includes('VELVET_RELEASE = "Native Story Experience"'));
check("Stories owns the document canvas while mounted", read("src/pages/Chats.jsx").includes('classList.add("velvet-burgundy-route")') && read("src/pages/Chats.jsx").includes('classList.remove("velvet-burgundy-route")'));
check("Burgundy background cannot end before the document", reference.includes('body.velvet-burgundy-route .app__content') && reference.includes('background: var(--stories-canvas) !important'));
check("Stories has designed Light Dark and Comfort palettes", ['data-theme="light"','data-theme="dark"','data-theme="comfort"'].every((token)=>reference.includes(token)) && ['--stories-canvas','--stories-panel','--stories-sidebar','--stories-nav'].every((token)=>reference.includes(token)));
check("desktop Stories sidebar is a full-height fixed app rail", reference.includes('body.velvet-burgundy-route .sidebar') && reference.includes('position: fixed !important') && reference.includes('height: 100dvh !important') && reference.includes('grid-column: 2 !important'));
check("Stories theme color follows the active theme", stories.includes('const { theme } = useTheme()') && stories.includes('light: "#f7eff2"') && stories.includes('comfort: "#eee4dc"') && stories.includes('dark: "#10090e"'));
check("dedicated Chats shares the themed full-canvas route", read("src/pages/ChatInbox.jsx").includes('classList.add("velvet-burgundy-route")') && read("src/pages/ChatInbox.jsx").includes('const { theme } = useTheme()'));
check("startup recovery boundary wraps the provider tree", read("src/main.jsx").includes("<VelvetErrorBoundary>") && read("src/components/VelvetErrorBoundary.jsx").includes("Repair & reopen Velvet"));
check("boot watchdog can recover before React mounts", read("index.html").includes("__VELVET_REPAIR_APP__") && read("index.html").includes("velvet_boot_repaired_v203"));
check("recovery clears service worker caches without deleting local storage", read("src/utils/runtimeRecovery.js").includes("getRegistrations") && read("src/utils/runtimeRecovery.js").includes("caches.keys") && !read("src/utils/runtimeRecovery.js").includes("localStorage.clear"));
check("Vercel revalidates app shell and service worker", read("vercel.json").includes("/index.html") && read("vercel.json").includes("/sw.js") && read("vercel.json").includes("no-cache, no-store"));
check("reload preserves the active Velvet destination", app.includes("readVelvetLocation") && app.includes("buildVelvetUrl") && app.includes('params.set("open", VELVET_PAGES.has(page) ? page : "chats")') && app.includes('window.history.pushState(nextState, "", nextUrl)'));
check("reload can restore an open character chat", app.includes('requested === "chat"') && app.includes('params.set("character", characterId)') && app.includes('setSelectedConversationId(locationState.conversationId || null)') && app.includes('characters.find((item) => item.id === locationState.characterId)'));
check("browser back forward stays synced with persistent URLs", app.includes('window.addEventListener("popstate", handleBrowserBack)') && app.includes('event.state?.velvetNavigation ? event.state : readVelvetLocation()'));

check("mobile navigation has the five reference destinations", ["Stories","Discover","Chats","Memories","Profile"].every((label)=>sidebar.includes(`label: "${label}"`)) && reference.includes("repeat(5, minmax(0,1fr))"));
check("mobile page controls are at least 44px", mobile.includes("button{min-height:44px}"));
check("mobile forms use sixteen pixel fields", mobile.includes("button,input,textarea,select{font-size:16px!important}"));
check("chat uses native document scrolling", mobile.includes("overflow-y:auto!important") && mobile.includes("touch-action:pan-y pinch-zoom!important") && mobile.includes(".app--chat .chat{display:block!important"));
check("chat content never becomes a nested scroller", mobile.includes(".chat__content,.chat__content--wallpaper") && mobile.includes("overflow:visible!important"));
check("mobile exit is portaled to body", chat.includes('createPortal((\n        <button type="button" className="chat__mobile-exit"') && mobile.includes("body>.chat__mobile-exit"));
check("mobile exit survives reading mode", mobile.includes("body>.chat__mobile-exit{opacity:1!important;visibility:visible!important}"));
check("header menu is a body portal", chat.includes('chat__menu-backdrop') && chat.includes('), document.body)}') && mobile.includes("body>.chat__menu-backdrop"));
check("header menu exposes Memories Relationship and AI Status", ["Memories 2.5","Relationship","AI Status"].every((label)=>chat.includes(label)));
check("message actions are a body portal", chat.includes("message-sheet-backdrop") && chat.includes("createPortal(("));
check("message sheet is guaranteed visible", mobile.includes("body>.message-sheet-backdrop>.message-sheet") && mobile.includes("transform:none!important") && mobile.includes("max-height:88dvh!important"));
check("message tap opens actions", chat.includes("onClick={handleMessageTap}") && chat.includes("onContextMenu"));
check("guarded swipe keeps vertical scrolling", chat.includes("Vertical movement always wins") && chat.includes("SWIPE_TRIGGER_PX = 72") && chat.includes("SWIPE_DIRECTION_RATIO = 1.8") && !chat.includes("preventDefault here")===false);
check("swipe touch surfaces declare pan-y", mobile.includes(".chat-message--swipeable{") && mobile.includes("touch-action:pan-y!important"));
check("composer has explicit three slot grid", mobile.includes("grid-template-columns:40px minmax(0,1fr) 44px!important") && mobile.includes(".chat__composer>textarea{grid-column:2!important") && mobile.includes(".chat__composer>.chat__send-button"));
check("composer accounts for keyboard and safe area", mobile.includes("--velvet-keyboard-offset") && mobile.includes("env(safe-area-inset-bottom)"));
check("short stories can flow directly into composer", chat.includes("chat--compact-mobile") && mobile.includes(".chat--compact-mobile .chat__composer{position:relative!important"));
check("scene director is portaled and phone sized", chat.includes("SCENE DIRECTOR") && chat.includes("directorNoteOpen && typeof document") && mobile.includes(".director-sheet{width:100%!important"));
check("scene director has all quick directions", ["More dialogue","More tension","Move scene","Bring someone in","Surprise me"].every((label)=>chat.includes(label)));
check("relationship engine is reachable from chat", chat.includes("chat__relationship-header") && chat.includes("setRelationshipOpen(true)"));
check("Memories uses the shared your MEMORIES library hero", memories.includes('reference-stories-title__script">your') && memories.includes("<h1>MEMORIES</h1>") && memories.includes("PRIVATE LIBRARY") && memories.includes("onBack"));
check("AI Status returns through history", app.includes("goBackOr") && app.includes('activePage === "diagnostics"') && diagnostics.includes("VELVET DOCTOR"));
check("AI diagnostics can clear stale PWA cache", diagnostics.includes("Clear app cache & reload") && diagnostics.includes('action: "diagnostics"'));
check("real AI stream telemetry remains enabled", edge.includes('liveStreaming: true') && edge.includes('type: "model"'));
check("UI does not call every 429 free quota exhaustion", !chat.includes("The free AI limit was reached") && !characterModal.includes("free limit was reached"));
check("Character Studio autosave remains present", characterModal.includes("velvet_character_draft_v18_") && characterModal.includes("Saved locally"));
check("Character Studio becomes full-screen on phone", mobile.includes(".character-studio{width:100%!important;height:100dvh!important"));
check("Stories matches the burgundy library structure", ["PRIVATE LIBRARY","COLLECTIONS","RECENT STORIES","Favorites","Archived","Trash"].every((label)=>stories.includes(label)) && reference.includes("reference-collections__grid") && reference.includes("grid-template-columns: repeat(3, minmax(0,1fr))"));
check("Stories has reference search filter and glowing new story action", stories.includes("Search a story, character or moment...") && stories.includes("reference-filter") && reference.includes("reference-stories-new"));
check("dedicated Chats destination exists and opens conversations", app.includes('activePage === "inbox"') && existsSync("src/pages/ChatInbox.jsx") && sidebar.includes('id: "inbox"'));
const inbox = read("src/pages/ChatInbox.jsx");
check("Chats keeps the shared your CHATS composition", inbox.includes('reference-stories-title__script">your') && inbox.includes("<h1>CHATS</h1>") && inbox.includes("PRIVATE LIBRARY") && reference.includes("reference-inbox--v2116"));
check("Chats has real search filters and one new chat action", inbox.includes("Search chats...") && ["Unread","Favorites","Archived"].every((label)=>inbox.includes(label)) && inbox.includes("onBrowseCharacters") && inbox.includes("reference-inbox__new-top") && !inbox.includes("reference-inbox__new-chat"));
check("Chats unread state is evidence based instead of fabricated", inbox.includes("READ_KEY_PREFIX") && inbox.includes('item.sender !== "user"') && inbox.includes("new Date(item.created_at).getTime() > seenAt") && chat.includes("velvet_chat_seen_v2114_") && !inbox.includes("Math.random"));
check("Chats keeps the exact Stories theme shell", inbox.includes('classList.add("velvet-burgundy-route")') && reference.includes("var(--stories-row)") && reference.includes("reference-inbox--v2116") && reference.includes("background: transparent !important"));
check("Chats phone layout stays inside the viewport", reference.includes(".reference-inbox.reference-inbox--v2116") && reference.includes("overflow-x: clip !important") && reference.includes("grid-template-columns: 50px minmax(0,1fr) 8px"));
check("Chats always labels rows with the character name", inbox.includes("<strong>{character.name}</strong>") && !inbox.includes("conversation.title || character.name"));
check("Chats uses one latest-message preview with time beside the name", inbox.includes("const lastMessage = clean(conversation.latest?.content") && inbox.includes("<time>{lastMessageAt}</time>") && inbox.includes("reference-inbox__preview") && !inbox.includes("You: {truncate"));
check("Chats filters are quiet text tabs on phone", reference.includes("reference-inbox__tabs--quiet") && reference.includes("background: transparent !important") && reference.includes("border-bottom: 1px solid") && !inbox.includes("<b>{count}</b>"));
check("Chats removes card-wall styling for a calmer inbox", reference.includes("reference-inbox__row--quiet") && reference.includes("border-radius: 0 !important") && reference.includes("box-shadow: none !important"));
check("Chats uses a tiny unread dot instead of count badges", inbox.includes("reference-inbox__status-dot") && !inbox.includes("conversation.unreadCount > 99") && reference.includes("width: 7px"));
check("Chats hero and rows are denser on phone", reference.includes("min-height: 112px !important") && reference.includes("min-height: 72px") && reference.includes("width: 50px") && reference.includes("height: 50px"));
check("Discover mobile feature stacks", mobile.includes(".discover-index__featured{grid-template-columns:1fr!important"));
check("Profile action buttons become full-width", mobile.includes(".profile-setting>button{grid-column:1/-1!important;width:100%!important"));
check("Settings controls do not squeeze", mobile.includes(".setting-row{align-items:stretch!important;flex-direction:column!important"));
const profile = read("src/pages/Profile.jsx");
const profileStyles = read("src/styles/profile.css");
check("Profile uses the shared your PROFILE library hero", profile.includes('className="chats-page chats-page--reference profile-reference-page"') && profile.includes('reference-stories-title__script">your') && profile.includes("<h1>PROFILE</h1>") && profile.includes("PRIVATE LIBRARY"));
check("Profile lives on the exact Stories theme route", profile.includes('classList.add("velvet-burgundy-route")') && profile.includes("const { theme } = useTheme()") && profileStyles.includes("var(--stories-panel-strong)"));
check("Profile stats come from real account data", profile.includes('supabase.from("conversations")') && profile.includes('supabase.from("memories")') && profile.includes("characters.length") && profile.includes("lorebooks.length") && !profile.includes("HOURS READ"));
check("Profile keeps real library destinations", ["My Characters","Roleplay Personas","World & Lorebooks","Memories","Settings","AI Status"].every((label)=>profile.includes(label)) && app.includes('onManageCharacters={() => navigate("characters")}'));
check("Profile editor persists auth metadata", profile.includes("supabase.auth.updateUser") && profile.includes("profile_tagline") && profile.includes("profile_quote") && profile.includes("avatar_url"));
check("Profile phone layout is compact and cannot widen the page", profileStyles.includes("overflow-x: clip !important") && profileStyles.includes("grid-template-columns: 86px minmax(0,1fr)") && profileStyles.includes("min-height: 118px !important"));
const memoryStyles = read("src/styles/memories.css");
check("Memories lives on the exact Stories shell", memories.includes('className="chats-page chats-page--reference memories-reference-page"') && memories.includes('classList.add("velvet-burgundy-route")') && memories.includes("const { theme } = useTheme()"));
check("Memories uses real pinned and recent memory sections", memories.includes("PINNED MEMORIES") && memories.includes("RECENT MEMORIES") && memories.includes("memory.is_pinned") && !memories.includes("The first song he played for me"));
check("Memories keeps full edit pin canon and delete controls", ["togglePinned", "toggleCanon", "openEdit", "deleteMemory", "Save memory"].every((token)=>memories.includes(token)));
check("Memories category counts come from real rows", memories.includes("groupCounts") && memories.includes("activeMemories.filter") && memories.includes("{groupCounts[id] || 0}") && !memories.includes("PINNED_MEMORIES_DEMO"));
check("Memories phone rails stay inside the viewport", memoryStyles.includes("overflow-x:clip!important") && memoryStyles.includes("grid-auto-columns:min(168px,48vw)") && memoryStyles.includes("grid-template-columns:62px minmax(0,1fr) 40px"));
check("Personas and Lore mobile grids are one column", mobile.includes(".persona-grid,.lorebook-grid,.lore-entry-grid{grid-template-columns:1fr!important"));
check("Diagnostics mobile grid is one column", mobile.includes(".diagnostics-hero,.diagnostics-grid{grid-template-columns:1fr!important"));
check("all major story drawers become phone sheets", [".memory-book,.timeline-drawer,.story-hub,.conversation-picker",".relationship-drawer",".chat-controls"].every((token)=>mobile.includes(token)));
check("PWA build cleans old caches", read("vite.config.js").includes("cleanupOutdatedCaches: true") && read("vite.config.js").includes("skipWaiting: true"));
check("reading mode still has persistent state", chat.includes('localStorage.getItem("velvet_reading_mode")') && chat.includes('localStorage.setItem("velvet_reading_mode"'));
check("immersive mode keeps chat header and three-dot menu visible", chat.includes("Immersive mode") && reference.includes(".chat--reading .chat__more") && reference.includes("transform: none !important"));
check("scene director rewrites latest reply in place", chat.includes("applyDirectorAndRegenerate") && chat.includes("regenerateCharacterReply(character.id, targetId, instruction, [])") && chat.includes("Rewrite last reply"));
check("scene director next beat queues direction for the next generation", chat.includes("const noteForThisGeneration = directorNote.trim();") && chat.includes("queueDirectorForNextBeat") && chat.includes("Save for the next reply"));
check("scene director keeps next beat tick and rewrite visible together", chat.includes("director-sheet__next-action") && chat.includes("director-sheet__rewrite-action") && chat.includes("<Check size={17}/>") && mobile.includes("director-sheet__dual-actions"));
check("queued next beat can be cleared from composer", chat.includes("chat__director-active") && chat.includes("clearQueuedDirector"));
check("AI replies stay as one complete visual message", read("src/components/RoleplayText.jsx").includes("roleplay-text--single-message") && !read("src/components/RoleplayText.jsx").includes("splitParagraphIntoBeats") && !read("src/components/RoleplayText.jsx").includes("findNextDialogueRange"));
check("all AI prose shares the same message surface", mobile.includes("the entire AI turn is one visual message") && mobile.includes(".chat-message--character p,.chat__content--wallpaper .chat-message--character p") && mobile.includes("width:fit-content!important"));
check("dialogue and narration are never split into separate bubbles", !mobile.includes("roleplay-text__beat--dialogue") && !mobile.includes("roleplay-text__beat--narration") && !read("src/components/RoleplayText.jsx").includes("roleplay-text__beat"));
check("AI inline roleplay formatting cannot create nested cards", mobile.includes(".roleplay-text__dialogue,.chat-message--character .roleplay-text__narration") && mobile.includes("background:none!important") && mobile.includes("box-shadow:none!important"));
check("full AI content remains one conversation turn", chat.includes('<RoleplayText content={message.content} />') && chat.includes('message.sender === "character"'));

const discoverPage = read("src/pages/MyCharacters.jsx");
const discoverStyles = read("src/styles/my-characters.css");
check("Discover uses the same hero language as Stories", discoverPage.includes("DiscoverReferenceHero") && discoverPage.includes("reference-stories-hero") && discoverPage.includes("reference-stories-title") && discoverPage.includes("<h1>STORIES</h1>") && discoverPage.includes("discover"));
check("Discover repeats the private-library identity", discoverPage.includes("PRIVATE LIBRARY") && discoverPage.includes("<Crown size={19}"));
check("Discover is calmer with Featured Popular and Vibes only", discoverPage.includes(">Featured<") && discoverPage.includes("Popular this week") && discoverPage.includes("Explore by vibe") && !discoverPage.includes("New for you") && !discoverPage.includes("FEATURED THIS WEEK"));
check("Discover keeps full real character actions", ["toggleFavorite", "onEditCharacter", "openTags", "handleDelete"].every((token)=>discoverPage.includes(token)));
check("Discover never fabricates popularity counts", !discoverPage.includes("fauxPopularity") && !discoverPage.includes("toFixed(1)") && !discoverPage.includes("↗"));
check("Discover has compact responsive phone cards", discoverStyles.includes("@media (max-width:760px)") && discoverStyles.includes("flex-basis:min(164px,44vw)") && discoverStyles.includes("flex-basis:min(196px,56vw)"));
check("Discover owns the shared theme route", discoverPage.includes('classList.add("velvet-burgundy-route", "velvet-discover-route")') && discoverPage.includes('classList.remove("velvet-burgundy-route", "velvet-discover-route")'));
check("Discover directly inherits Stories theme tokens", discoverStyles.includes("--discover-canvas: var(--stories-canvas") && discoverStyles.includes("--discover-search: var(--stories-search") && discoverStyles.includes("--discover-panel: var(--stories-panel"));
check("Discover hides secondary filters behind More", discoverPage.includes("showMore") && discoverPage.includes("discover-burgundy__more-filters") && discoverPage.includes("Trash"));
check("Discover desktop content stays editorial", discoverStyles.includes("width: min(1040px, 100%)"));
check("Discover mounts on the exact Stories canvas", discoverPage.includes("chats-page chats-page--reference discover-burgundy") && discoverStyles.includes("exact Stories") && !discoverStyles.includes("--discover-page-bg") && !discoverStyles.includes("discover-burgundy::before"));
check("Discover does not repaint the sidebar", !discoverStyles.includes("body.velvet-discover-route .sidebar") && reference.includes("body.velvet-burgundy-route .sidebar"));
check("Discover hero keeps Stories line spark and new-story button", discoverPage.includes("reference-stories-title__line") && discoverPage.includes("reference-stories-title__spark") && discoverPage.includes("reference-stories-new"));
check("Discover mobile title and rails cannot widen the page", discoverStyles.includes("overflow-x: clip") && !discoverStyles.includes("margin-right:-14px"));
check("Discover phone hero is compact without changing Stories", discoverStyles.includes(".discover-reference-hero {\n    min-height: 124px !important") && discoverStyles.includes("margin-bottom: 8px !important") && discoverStyles.includes("font-size: clamp(2.75rem, 13vw, 3.65rem)"));

const nativeStyles = read("src/styles/velvet-v220.css");
const characterDetail = read("src/pages/CharacterDetail.jsx");
check("secondary Velvet routes are lazy loaded", app.includes('lazy(() => import("./pages/Chat"))') && app.includes('lazy(() => import("./pages/Settings"))') && app.includes('<Suspense fallback={<VelvetRouteLoading />}>' ));
check("native experience override loads after the burgundy reference", main.includes('import "./styles/velvet-v220.css";') && main.lastIndexOf("velvet-v220.css") > main.lastIndexOf("velvet-burgundy-reference.css"));
check("chat header keeps character name as the primary identity", chat.includes("chat__character-name-button--primary") && chat.includes("<strong>{character.name}</strong>") && nativeStyles.includes(".chat__reading-button,.chat__memory-book-button,.chat__relationship-header{display:none!important}"));
check("chat has subtle per-character presence instead of separate skins", chat.includes("--character-presence-color") && chat.includes("--character-presence-image") && nativeStyles.includes("--chat-presence-wash") && nativeStyles.includes("opacity:.055"));
check("Scene Director is integrated into the composer", chat.includes('<span>Direct</span>') && nativeStyles.includes(".chat__director-trigger") && chat.includes("Next beat") && chat.includes("Rewrite last reply"));
check("character landing continues the real latest story", characterDetail.includes("const latestStory = stories[0] || null") && characterDetail.includes("Continue latest story") && characterDetail.includes("character-profile__story-signature"));
check("new story setup can keep or replace the opening beat", characterDetail.includes("story-setup-sheet") && characterDetail.includes("Original opening") && characterDetail.includes("Custom opening") && characterDetail.includes("storyOpening.trim() || character.firstMessage"));
check("character and settings screens inherit the shared Stories shell", characterDetail.includes('classList.add("velvet-burgundy-route")') && settings.includes('classList.add("velvet-burgundy-route")'));
check("Character Studio exposes the five-step editorial journey", characterModal.includes("character-studio__journey") && ["Essence","Relationship","Depth","Voice","Opening"].every((label)=>characterModal.includes(`\"${label}\"`)) && characterModal.includes("jumpStudio"));
check("Create with AI stays a first-class Character Studio action", characterModal.includes("Create with AI") && nativeStyles.includes(".character-studio__ai--primary") && nativeStyles.includes(".character-studio__creator"));
check("Settings is organized into four calm destinations", settings.includes("settings-page__nav") && ["Appearance","Storytelling","AI & app","Privacy"].every((label)=>settings.includes(`>${label}<`)) && nativeStyles.includes(".settings-page--editorial"));
check("native layer adds cheap rendering wins", nativeStyles.includes("content-visibility:auto") && nativeStyles.includes("contain-intrinsic-size") && nativeStyles.includes("velvet-page-enter"));

let failed=0;
for (const item of checks) { console.log(`${item.pass ? "PASS" : "FAIL"}  ${item.name}`); if(!item.pass) failed++; }
if(failed){ console.error(`\n${failed} UI checks failed.`); process.exit(1); }
console.log(`\n${checks.length} UI checks passed.`);

