import { existsSync, readFileSync } from "node:fs";

const read = (file) => readFileSync(file, "utf8");
const main = read("src/main.jsx");
const app = read("src/App.jsx");
const chat = read("src/pages/Chat.jsx");
const mobile = read("src/styles/velvet-mobile-foundation.css");
const reference = read("src/styles/velvet-burgundy-reference.css");
const stories = read("src/pages/Chats.jsx");
const sidebar = read("src/components/Sidebar.jsx");
const settings = read("src/pages/Settings.jsx");
const memories = read("src/pages/Memories.jsx");
const diagnostics = read("src/pages/Diagnostics.jsx");
const characterModal = read("src/components/CreateCharacterModal.jsx");
const edge = read("supabase/functions/character-chat/index.ts");
const pkg = JSON.parse(read("package.json"));

const checks = [];
const check = (name, pass) => checks.push({ name, pass: Boolean(pass) });

check("burgundy reference layer is the final stylesheet", main.includes('import "./styles/velvet-burgundy-reference.css";') && main.lastIndexOf("velvet-burgundy-reference.css") > main.lastIndexOf("velvet-mobile-foundation.css"));
check("legacy mobile hotfix styles are no longer loaded", ["mobile-v71.css","velvet-v171-hotfix.css","velvet-v172-mobile-emergency.css","velvet-v181-guarded-swipe.css","velvet-v19-phone-first.css","velvet-v191-composer-hotfix.css","velvet-v192-message-sheet-portal.css","velvet-v193-mobile-geometry.css"].every((name)=>!main.includes(name)));
check("legacy mobile hotfix files were removed", ["mobile-v71.css","velvet-v171-hotfix.css","velvet-v172-mobile-emergency.css","velvet-v181-guarded-swipe.css","velvet-v19-phone-first.css","velvet-v191-composer-hotfix.css","velvet-v192-message-sheet-portal.css","velvet-v193-mobile-geometry.css"].every((name)=>!existsSync(`src/styles/${name}`)));
check("release is v2.1.1 burgundy full-canvas fix", pkg.version === "2.1.1" && read("src/config/version.js").includes('VELVET_RELEASE = "Burgundy Full-Canvas Fix"'));
check("Stories owns the document canvas while mounted", read("src/pages/Chats.jsx").includes('classList.add("velvet-burgundy-route")') && read("src/pages/Chats.jsx").includes('classList.remove("velvet-burgundy-route")'));
check("Burgundy background cannot end before the document", read("src/styles/velvet-burgundy-reference.css").includes('body.velvet-burgundy-route .app__content') && read("src/styles/velvet-burgundy-reference.css").includes('background: #0f090e !important'));
check("startup recovery boundary wraps the provider tree", read("src/main.jsx").includes("<VelvetErrorBoundary>") && read("src/components/VelvetErrorBoundary.jsx").includes("Repair & reopen Velvet"));
check("boot watchdog can recover before React mounts", read("index.html").includes("__VELVET_REPAIR_APP__") && read("index.html").includes("velvet_boot_repaired_v203"));
check("recovery clears service worker caches without deleting local storage", read("src/utils/runtimeRecovery.js").includes("getRegistrations") && read("src/utils/runtimeRecovery.js").includes("caches.keys") && !read("src/utils/runtimeRecovery.js").includes("localStorage.clear"));
check("Vercel revalidates app shell and service worker", read("vercel.json").includes("/index.html") && read("vercel.json").includes("/sw.js") && read("vercel.json").includes("no-cache, no-store"));

check("mobile navigation has the five reference destinations", ["Stories","Discover","Chats","Memories","Profile"].every((label)=>sidebar.includes(`label: "${label}"`)) && reference.includes("repeat(5, minmax(0,1fr))"));
check("mobile page controls are at least 44px", mobile.includes("button{min-height:44px}"));
check("mobile forms use sixteen pixel fields", mobile.includes("button,input,textarea,select{font-size:16px!important}"));
check("chat uses native document scrolling", mobile.includes("overflow-y:auto!important") && mobile.includes("touch-action:pan-y pinch-zoom!important") && mobile.includes(".app--chat .chat{display:block!important"));
check("chat content never becomes a nested scroller", mobile.includes(".chat__content,.chat__content--wallpaper") && mobile.includes("overflow:visible!important"));
check("mobile exit is portaled to body", chat.includes('createPortal((\n        <button type="button" className="chat__mobile-exit"') && mobile.includes("body>.chat__mobile-exit"));
check("mobile exit survives reading mode", mobile.includes("body>.chat__mobile-exit{opacity:1!important;visibility:visible!important}"));
check("header menu is a body portal", chat.includes('chat__menu-backdrop') && chat.includes('), document.body)}') && mobile.includes("body>.chat__menu-backdrop"));
check("header menu exposes Memories Relationship and AI Status", ["Memories 2.5","Relationship","AI Status"].every((label)=>chat.includes(label)));
check("message actions are a body portal", chat.includes("message-sheet-backdrop") && chat.includes("createPortal(("));
check("message sheet is guaranteed visible", mobile.includes("body>.message-sheet-backdrop>.message-sheet") && mobile.includes("transform:none!important") && mobile.includes("max-height:88dvh!important"));
check("message tap opens actions", chat.includes("onClick={handleMessageTap}") && chat.includes("onContextMenu"));
check("guarded swipe keeps vertical scrolling", chat.includes("Vertical movement always wins") && chat.includes("SWIPE_TRIGGER_PX = 72") && chat.includes("SWIPE_DIRECTION_RATIO = 1.8") && !chat.includes("preventDefault here")===false);
check("swipe touch surfaces declare pan-y", mobile.includes(".chat-message--swipeable{") && mobile.includes("touch-action:pan-y!important"));
check("composer has explicit three slot grid", mobile.includes("grid-template-columns:40px minmax(0,1fr) 44px!important") && mobile.includes(".chat__composer>textarea{grid-column:2!important") && mobile.includes(".chat__composer>.chat__send-button"));
check("composer accounts for keyboard and safe area", mobile.includes("--velvet-keyboard-offset") && mobile.includes("env(safe-area-inset-bottom)"));
check("short stories can flow directly into composer", chat.includes("chat--compact-mobile") && mobile.includes(".chat--compact-mobile .chat__composer{position:relative!important"));
check("scene director is portaled and phone sized", chat.includes("SCENE DIRECTOR") && chat.includes("directorNoteOpen && typeof document") && mobile.includes(".director-sheet{width:100%!important"));
check("scene director has all quick directions", ["More dialogue","More tension","Move scene","Bring someone in","Surprise me"].every((label)=>chat.includes(label)));
check("relationship engine is reachable from chat", chat.includes("chat__relationship-header") && chat.includes("setRelationshipOpen(true)"));
check("Memories 2.5 is named and has back navigation", memories.includes("Memories 2.5") && memories.includes("memories-page__back") && app.includes('onBack={() => goBackOr("profile")}'));
check("AI Status returns through history", app.includes("goBackOr") && app.includes('activePage === "diagnostics"') && diagnostics.includes("VELVET DOCTOR"));
check("AI diagnostics can clear stale PWA cache", diagnostics.includes("Clear app cache & reload") && diagnostics.includes('action: "diagnostics"'));
check("real AI stream telemetry remains enabled", edge.includes('liveStreaming: true') && edge.includes('type: "model"'));
check("UI does not call every 429 free quota exhaustion", !chat.includes("The free AI limit was reached") && !characterModal.includes("free limit was reached"));
check("Character Studio autosave remains present", characterModal.includes("velvet_character_draft_v18_") && characterModal.includes("Saved locally"));
check("Character Studio becomes full-screen on phone", mobile.includes(".character-studio{width:100%!important;height:100dvh!important"));
check("Stories matches the burgundy library structure", ["PRIVATE LIBRARY","COLLECTIONS","RECENT STORIES","Favorites","Archived","Trash"].every((label)=>stories.includes(label)) && reference.includes("reference-collections__grid") && reference.includes("grid-template-columns: repeat(3, minmax(0,1fr))"));
check("Stories has reference search filter and glowing new story action", stories.includes("Search a story, character or moment...") && stories.includes("reference-filter") && reference.includes("reference-stories-new"));
check("dedicated Chats destination exists and opens conversations", app.includes('activePage === "inbox"') && existsSync("src/pages/ChatInbox.jsx") && sidebar.includes('id: "inbox"'));
check("Discover mobile feature stacks", mobile.includes(".discover-index__featured{grid-template-columns:1fr!important"));
check("Profile action buttons become full-width", mobile.includes(".profile-setting>button{grid-column:1/-1!important;width:100%!important"));
check("Settings controls do not squeeze", mobile.includes(".setting-row{align-items:stretch!important;flex-direction:column!important"));
check("Memories mobile grid is one column", mobile.includes(".memory-grid{grid-template-columns:1fr!important"));
check("Personas and Lore mobile grids are one column", mobile.includes(".persona-grid,.lorebook-grid,.lore-entry-grid{grid-template-columns:1fr!important"));
check("Diagnostics mobile grid is one column", mobile.includes(".diagnostics-hero,.diagnostics-grid{grid-template-columns:1fr!important"));
check("all major story drawers become phone sheets", [".memory-book,.timeline-drawer,.story-hub,.conversation-picker",".relationship-drawer",".chat-controls"].every((token)=>mobile.includes(token)));
check("PWA build cleans old caches", read("vite.config.js").includes("cleanupOutdatedCaches: true") && read("vite.config.js").includes("skipWaiting: true"));
check("reading mode still has persistent state", chat.includes('localStorage.getItem("velvet_reading_mode")') && chat.includes('localStorage.setItem("velvet_reading_mode"'));
check("AI replies stay as one complete visual message", read("src/components/RoleplayText.jsx").includes("roleplay-text--single-message") && !read("src/components/RoleplayText.jsx").includes("splitParagraphIntoBeats") && !read("src/components/RoleplayText.jsx").includes("findNextDialogueRange"));
check("all AI prose shares the same message surface", mobile.includes("the entire AI turn is one visual message") && mobile.includes(".chat-message--character p,.chat__content--wallpaper .chat-message--character p") && mobile.includes("width:fit-content!important"));
check("dialogue and narration are never split into separate bubbles", !mobile.includes("roleplay-text__beat--dialogue") && !mobile.includes("roleplay-text__beat--narration") && !read("src/components/RoleplayText.jsx").includes("roleplay-text__beat"));
check("AI inline roleplay formatting cannot create nested cards", mobile.includes(".roleplay-text__dialogue,.chat-message--character .roleplay-text__narration") && mobile.includes("background:none!important") && mobile.includes("box-shadow:none!important"));
check("full AI content remains one conversation turn", chat.includes('<RoleplayText content={message.content} />') && chat.includes('message.sender === "character"'));

let failed=0;
for (const item of checks) { console.log(`${item.pass ? "PASS" : "FAIL"}  ${item.name}`); if(!item.pass) failed++; }
if(failed){ console.error(`\n${failed} UI checks failed.`); process.exit(1); }
console.log(`\n${checks.length} UI checks passed.`);
